### ISSUE TITLE
pdf20-utf8-test.pdf

### ISSUE THREAD

**Issue by lunter2** [pdf-association/pdf20examples#10]
Try open: https://github.com/pdf-association/pdf20examples/blob/master/pdf20-utf8-test.pdf
in latest Adobe Acrobat Reader DC 2024.002.20687

UTF-8 characters are not displayed correctly.

Does the latest Adobe Reader not support the PDF 2.0 specification created by Adobe?

**Comment by petervwyatt** [comment]
Yes.
But PDF 2.0 was **_not_** created by Adobe!! It was created in a vendor-neutral ISO forum with many stakeholders and experts reached consensus. There are [lots of PDF 2.0 implementations](https://pdfa.org/supporting-pdf20/).

**Comment by petervwyatt** [comment]
This is a specific vendor problem.
