### ISSUE TITLE
Files that do not conform to ISO 32000-2:2017

### ISSUE THREAD

**Issue by a20god** [pdf-association/pdf20examples#4]
There are a couple of problems:

PDF 2.0 UTF-8 string and annotation.pdf: (a) (b) (d) (e)
PDF 2.0 image with BPC.pdf: (a) (b)
PDF 2.0 via incremental save.pdf: (b) (c)
PDF 2.0 with offset start.pdf: (a) (b)
PDF 2.0 with page level output intent.pdf: (a) (b)
Simple PDF 2.0 file.pdf: (a) (b)

(a) "%%EOF" is supposed to be the last *line* of the document, therefore it must be followed by CR, LF, or CR LF (7.5.5)
(b) ID is required in PDF 2.0 (7.5.5)
(c) incorrect offset after startx (7.5.5)
(d) Metadata is supposed to be wrapped in an XMP packet [citation needed]
(e) Resources is required in page object (7.7.3.3)

**Comment by pdfa-mattk** [comment]
Thanks @a20god for the observations and proofreading. To your points specifically:
(a) This is a bit open to interpretation, IMO, as 7.5.5 states that the last line shall only contain the EOF marker. I can see how 7.5.1 would imply that the term "line of the file" supersedes the "only contain" term in 7.5.5. Certainly I don't see any harm in adding a CR/LF to be clear, and many PDF 1.x files do just this. I'll do so.
(b) Great catch, thanks! I'll add these.
(c) I don't seem to be seeing a bad offset here, if you could let me know which looks incorrect (I assume you meant after one of the "startxref" entries), it'd be appreciated.
(d) Can you elaborate on this? My read of the Adobe XMP: Extensible Metadata Platform, Part 3 indicates that the wrapper - the xpacket header/trailer & whitespace - is not formally required. Maybe there's something in ISO 16684-1 that you're seeing that overrides or negates this?
(e) It's legal to inherit from the page tree parent, but bad practice. I'll shift the resources down to the page dictionary in a PR.

**Comment by a20god** [comment]
(a) 7.5.1: "Each line shall be terminated by an end-of-line (EOL) marker". That is, everything following the last EOL marker is not in the last line as the last line ends at that EOL marker.
7.5.5: "The last line of the file shall contain only the end-of-file marker, %%EOF".
That is, %%EOF must come before the last EOL.

(c) The file contains 5223 bytes, the offset after startxref is 5262 and therefore clearly does not point to the xref keyword, it does not point into the document at all.

(d) The real problem with the metadata of "PDF 2.0 UTF-8 string and annotation.pdf" is that the stream has an incorrect Length entry which causes the endstream and endobj keywords to be part of the stream contents!

(e) yes, Resources is inheritable. Sorry.

**Comment by pdfa-mattk** [comment]
(c) it looks like this is a git issue at core - git is not recognizing this as a binary file and is trying to automatically change line breaks. I'll add a .gitattributes to mark these as binary.
For (d), thanks for pointing the incorrect length out. I'll correct it.

**Comment by pdfa-mattk** [comment]
@a20god I believe the issues in this issue are all resolved in PR #5. I'll leave this issue open for a few days just in case.

**Comment by a20god** [comment]
Looks good now!
