### ISSUE TITLE
PDF spec appendix examples

### ISSUE THREAD

**Issue by caspervanpomeren** [pdf-association/pdf20examples#6]
I am currently working through the PDF spec and these examples are great in my journey of getting a better understanding of the PDF format. So thanks for that.

Part of the spec is the following annex: "Annex H Example PDF files". I am trying to create a working example of all these examples, just like this github repository. I have managed to recreate most of the examples, but unfortunately I haven't been able to recreate the example in: "H.8.2 Table of Contents".  

So I have some questions:

1. Are there any examples like this repository for the annex examples inside the PDF spec? 
2. Are there any examples like this repository with a working Table of Contents / Nested lists?

Thanks in advance

**Comment by pdfa-mattk** [comment]
Hello @caspervanpomeren. Unfortunately the examples in the PDF specification are not available in any public repository. ISO owns the copyright for the 32000-2 (PDF 2.0) standard, including the annex examples, and the rights to publish them.
There's no example of a PDF 2.0 table of contents or nested list that I'm aware of. We'd be happy to have a PR to add an example, if you happen to create one.

**Comment by caspervanpomeren** [comment]
Thanks for the quick response @pdfa-mattk . That's unfortunate, but i'll keep looking/searching for a solution. I just can't get the Table of Contents to show up on my page. I suspect I should probably give the table of contents some coordinates, because without them it logically doesn't show in the page. Thing is, I don't quite get how/ where to place these coordinates (if that's even the problem).

If I do happen to succeed in remaking similar examples to the annex, i'll make a PR. Just need some more time to figure it all out.

**Comment by caspervanpomeren** [comment]
Maybe @a20god has some input, he seems quite knowledgeable on the subject as well. Otherwise we can close this issue and then i'll make the PR when I manage to recreate a working H.8.2 Table of Contents example.

**Comment by pdfa-mattk** [comment]
Closing per discussion.
