### ISSUE TITLE
Example of encrypted document?

### ISSUE THREAD

**Issue by benwiggy** [pdf-association/pdf20examples#8]
Could we have an example of a v2.0 PDF document that is password protected? (Obviously, with the password made available!)

It would be useful to test whether PDF viewers can decrypt them.

**Comment by petervwyatt** [comment]
Please also see iText test suite: https://github.com/itext/itext7/tree/develop/kernel/src/test/resources/com/itextpdf/kernel/crypto/PdfEncryptionTest
